spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  cloud:
    consul:
      #host: 127.0.0.1
      #port: 8500
      discovery:
        health-check-interval: 100s
  jpa:
    show-sql: true
    properties:
      hibernate:
 #       default_schema: emdm #blueprint  # If you want a default schema
        ddl-auto: create-drop
  jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS : false
  application:
    name: graphql 
server:
    port: 8888
    
endpoints:
  health:
    enabled: true
api:
  movieDbApi: xyz
  omDbApi: xyz
  
swagger:
  api:
    base:
      package: com.dc.blueprint.api
    path: /*  
    title: Blueprint REST API
    description: Spring Boot REST API for Blueprint
    version: 1.0
    termsofservice:
      url: Terms of service
    contact:
      name: DC
      url:  #https://github
      email: dwaip@yahoo.com
    license:
      name: 
      url: 

    